version: "3.2"

services:
    backend:
        build: ./
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./:/usr/src/
        ports:
          - 8000:8000
        env_file:
          - ./.env.dev

    front_end:
        build:
            context: ./front_end
        volumes:
            - build_folder:/front_end/build
        command: npm run-script build

    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.dev

    nginx:
        image: nginx:latest
        ports:
            - 80:8080
        volumes:
            - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - build_folder:/var/www/front_end/
        depends_on:
            - backend
            - front_end

volumes:
    postgres_data:
    build_folder:
