version: "3.2"

services:
    backend:
        image: python:3.7
        # user: python
        build: ./app
        working_dir: /home/python/dev
        volumes:
          - ./:/usr/src/
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
        env_file:
            - ./.env.dev
        command: bash -c "
            pip install -r requirements.txt
            && python3 manage.py runserver 0.0.0.0:8000"
    front_end:
        build: ./front_end
        user: node
        working_dir: /home/node/dev
        volumes:
            - ./front_end:/home/node/dev
            - ./front_end/node_modules
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        depends_on:
            - backend
        tty: true
        command: npm start

    db:
        image: postgres:12.4-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.dev

volumes:
    postgres_data:
